language: python
python:
- 3.6
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y sqlite3
install:
- pip install codecov
- pip install -U tox-travis
script: tox
after_success:
- codecov
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: davidemoro
  password:
    secure: iwfqDvyBjPK/y/ZeiINFEIrLhB056SMLZ2AI8tzYcSFvDVfpU1OBsrGjE5uPtDNwmqIabsZ+D2pcbWkfiqSw0ofgQJizXl1/anv0LAG1mhkkfX2NUGWnigGyadg1hKoj4S1ElyGRjoJ9jWcKTXkGg6YJcaJ0PlWO75g3SYbui+6nosfD7YnGygLC80WKQ7JHjH0jjUCn88zaodLS8zyoG3uaCsUcyIWh2iz0qCjBtJ3KNoyf9wh2Q/HUJqWtEDvBQTU6ROE4GYE/lXJQVhMkpJpgHj3WbMdYuGwg04Otwh/4LTGYCUvKCX69PFmKikcj+tk/R7X8nhl4mG3ey/4XPmSZhE2bNWPqxgOTpDHzRh2LUhrRF51QOSywKldQgVaxohwg1sXhcr7ilH5VSl4RyIDbeJqX4Kxwsi9YuutbH6ezAdnyk5KxxKIuLXJ/kni5qdgwq01YwGSnM+pJf/Y2ZW/9pTKTmc4UHSmnjPRns/yWafN2dCH4kz+jm0IuQLHO752B7R5QvcZRNahY0NJMqB/06aG7IgijHWU5ZGG4cs69K6cC3G7Qqq/HtXLw6zIlOhik80JjTqs9QhGjs6l/ktFnH709PNPtMCcw8W84l3GKAGH41LvncpwoeLXZ0ZYgp+ZdG/SeZdtRBAT+6g2Wa/pylvAI8ZLQtMvZSgpJHGE=
  on:
    tags: true
    repo: davidemoro/play_sql
    python: 3.6
